# #Assignment-1

In [1]:
#1.Write a NumPy program to reverse an array (first element becomes last).
import numpy as np
a=np.array([1,2,3,4,5])
print("revese of array is:")
print(a[::-1])

revese of array is:
[5 4 3 2 1]


In [2]:
#2.Write a NumPy program to convert an array to a float type. 
ar=np.array([1,2,3,45,5],dtype='float')
print(ar)

[ 1.  2.  3. 45.  5.]


In [3]:
#3.Write a NumPy program to append values to the end of an array.
a=np.array([1,2,3,4,5])
b=np.append(a,7)
print(b)

[1 2 3 4 5 7]


In [38]:
#4.Write a NumPy program to create an array with values ranging from 12 to 38.
a=np.arange(12,39)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [5]:
#5.Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.
a1=np.array([[1,2,3,4],[4,5,6,7]])
print(a1)
print("______________")

print(np.min(a1,axis=1))
print(np.max(a1,axis=1))


[[1 2 3 4]
 [4 5 6 7]]
______________
[1 4]
[4 7]


In [9]:
#6.Write a NumPy program to convert 1-D arrays as columns into a 2-D array.
a1=np.arange(5,15).reshape(2,5)
print('a1:',a1)


a1: [[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [10]:
#7.Write a NumPy program to stack 1-D arrays as row wise. 
a1=np.arange(1,10)
print(a1)
print(np.vstack(a1))

[1 2 3 4 5 6 7 8 9]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [11]:
#8.Write a NumPy program to get the minimum and maximum value of a given array along the second axis. 
#Expected Output:
#Original array:
#[[0 1]
#[2 3]]
#Maximum value along the second axis:
#[1 3]
#Minimum value along the second axis:
#[0 2]
a=np.arange(0,4).reshape(2,2)
print(a)
print("minimun is",np.min(a,1))
print("maximum is",np.max(a,1))

[[0 1]
 [2 3]]
minimun is [0 2]
maximum is [1 3]


In [ ]:
#9.Write a NumPy program (using NumPy) to sum of all the multiples of 3 or 5 below 100. 
a=np.arange(1,100)
s=a[(a%3==0)|(a%5==0)]

print(s)
print("sum is",np.sum(s))

In [34]:
#10.Write a NumPy program to concatenate two 2-dimensional arrays. 
a1=np.random.randint(5,25,15).reshape(5,3)
a2=np.random.randint(200,215,15).reshape(5,3)
print(np.concatenate([a1,a2]))

[[ 16   7  20]
 [ 12  19  22]
 [ 23  17  14]
 [ 18  10  10]
 [ 12  24  15]
 [213 208 209]
 [213 213 209]
 [208 212 202]
 [212 206 202]
 [212 210 211]]


In [35]:
#11.Write a NumPy program to test element-wise for NaN of a given array.
a1=np.array([0,np.nan,4])
print(a1)
print(np.isnan(a1))

[ 0. nan  4.]
[False  True False]


In [36]:
#12.Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
a1=np.array([1,2,3,4])
a2=np.array([2,4])
print(np.in1d(a1,a2))

[False  True False  True]


In [37]:
#13.Write a NumPy program to create a contiguous flattened array
a=np.random.randint(5,16,(4,4))
print(a)
s1=a.flatten()
print(s1)

[[13  5 13 12]
 [ 6  6  9 14]
 [12 12 14 13]
 [ 8  7  7  9]]
[13  5 13 12  6  6  9 14 12 12 14 13  8  7  7  9]


In [12]:
#14.Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.  Checkerboard pattern:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
#15.Write a NumPy program to compute the inner product of two given vectors 
x = np.array([4, 5])
y = np.array([7, 10])
print(x)
print(y)
print("Inner product of said vectors:")
print(np.dot(x, y))

[4 5]
[ 7 10]
Inner product of said vectors:
78


In [33]:
#16.Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
x = np.ones((5,5))
print("Original array:\n",x)
print('   ______________')
x[1:-1,1:-1] = 0
print(x)

Original array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
   ______________
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
#17.Write a NumPy program to append values to the end of an array.
x = [10, 20, 30]
print("Original array:",x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("After::",x)


Original array: [10, 20, 30]
After:: [10 20 30 40 50 60 70 80 90]


In [ ]:
#18.Write a NumPy program to get the unique elements of an array. 
a=np.array([1,1,2,3,4,8,8])
b=np.unique(a)
print(b)

In [27]:
#19.Write a NumPy program to get the index of a maximum element in a NumPy array along one axis.
a=np.arange(0,4).reshape(2,2)
print(a)
i,j=np.unravel_index(a.argmax(),a.shape)
print('max:',a[i,j])

[[0 1]
 [2 3]]
max: 3
