In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
print(np.__version__)

1.22.1


In [38]:
#creation of array 
a=np.array([1,2,3,4,5,6])
print(type(a))
print(a)
print(a.ndim)#gives dimension
print(a.shape)#in tuple form and gives number of col

<class 'numpy.ndarray'>
[1 2 3 4 5 6]
1
(6,)


In [19]:
#accesing
print(a[0])

1


In [20]:
#length
print(len(a))

6


In [29]:
#slicing
print(a[::2])
print(a[1::2])
#reverse
print(a[::-1])
a[1]=10
print(a)

[1 3 5]
[10  4  6]
[ 6  5  4  3 10  1]
[ 1 10  3  4  5  6]


In [39]:
a2=np.array([2,"ok",455.5,5])
print(a2)
print(type(a2[0]))
print(type(a2))
print(type(a2.dtype))#gives type of the every element in array
print((a.dtype))

['2' 'ok' '455.5' '5']
<class 'numpy.str_'>
<class 'numpy.ndarray'>
<class 'numpy.dtype[str_]'>
int32


In [41]:
a=np.array([1,2,3,4,5,6],dtype='float')
print(a.dtype)

float64


In [44]:
a[1]=10.4

In [45]:
print(a)

[ 1.  10.4  3.   4.   5.   6. ]


In [59]:
#for loop
sum=0.0
for i in range(0,len(a)):
    pass
    #print(a[i])
    #sum+=i
print('sum is:',sum)

print(a.sum())
    
    

sum is: 0.0
29.4


In [80]:
#even elements
b=np.array([2,4,6,1,10,99])
for i in range(len(b)):
    if(b[i]%2==0):
        print(b[i],end=" ")

2 4 6 10 

In [112]:
secarr = np.array([1,2,3,4])
print("Array Items = ", secLarr)

first = second = min(secLarr)

for i in range(len(secarr)):
    if (secarr[i] > first):
        second = first
        first = secarr[i]
    elif(secarr[i] > second and secarr[i] < first):
        second = secarr[i]

print(" Largest  ", first)
print(" Second Largest ", second)

Array Items =  [1 2 3 4]
 Largest   4
 Second Largest  3


In [129]:
#array of table
a=[]

n=int(input("enter number:"))
for i in range(1,11):
    r=n*i
    a.append(r)
    b3=np.array(a)
print(b3,end=" ")
print(type(b3))
print("-------------")
b1=a[6:]
b2=np.array(a[6:])
#b1.copy()
#print(b1)
print(b2)
print(type(b2))



enter number:8
[ 8 16 24 32 40 48 56 64 72 80] <class 'numpy.ndarray'>
-------------
[56 64 72 80]
<class 'numpy.ndarray'>


In [5]:
a=np.array(('shreya','nagma'))
print(type(a))
print(a.dtype)#string
print(a)

<class 'numpy.ndarray'>
<U6
['shreya' 'nagma']


In [6]:
arr=np.zeros(2)
print(arr)

[0. 0.]


In [8]:
arr1=np.ones(3)
arr2=np.ones(3,dtype=int)
print(arr1)
print(arr2)

[1. 1. 1.]
[1 1 1]


In [18]:
arr1[[1,2]]=[10,20]
print(arr1)
print(arr1[2])
print(arr1[1::-1])


[ 1. 10. 20.]
20.0
[10.  1.]


In [21]:
print(arr1.shape)

(3,)


In [128]:
#2d array
a2d=np.array([[1,2,3],[4,5,6]])
print(a2d[1:1])
print(a2d)

[]
[[1 2 3]
 [4 5 6]]


In [29]:
print("array is:",a2d.ndim)
print("shape is:",a2d.shape)


array is: 2
shape is: (2, 3)


In [79]:
ar_zero=np.zeros((3))
ar1_zero=np.zeros((3),dtype=int)
print(ar1_zero)
print(ar_zero)
ar_one=np.ones(3)
print(ar_one)
ar_one[1]=10
print(ar_one)
ar_one[[1,2]]=[10,20]
print(ar_one)

[0 0 0]
[0. 0. 0.]
[1. 1. 1.]
[ 1. 10.  1.]
[ 1. 10. 20.]


In [82]:
#arrage---generates 1 -d array always
a=np.arange(5,51,5)
print(a)
print("dimension is:",a.ndim)

[ 5 10 15 20 25 30 35 40 45 50]
dimension is: 1


In [47]:
#conversion of 1d to 2d
a2=a.reshape(3,3)#doesnt change original array
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [71]:
#array 2d random
arr2d=np.random.randint(1,10,(5,5))
print(arr2d)
print(np.min(arr2d,axis=0))

[[6 7 1 8 9]
 [1 3 8 7 5]
 [3 5 4 4 5]
 [2 9 1 7 8]
 [8 4 5 1 3]]
[1 3 1 1 3]


In [67]:
a=np.array([1,21,3,4])
s=np.sum(a)
print(s)


29


In [69]:
print(np.mean(a))
print(np.min(a))
print(np.max(a))
print("before sort:",a)
print("after sort:",np.sort(a))


7.25
1
21
before sort: [ 1 21  3  4]
after sort: [ 1  3  4 21]


In [205]:
arr=np.zeros(len(np.arange(11,31,2)),dtype=int)
print(id(arr))
print(arr)
for i in range(0,len(arr)):
   
    arr[i%2!=0]=np.arange(11,31,2)
print(arr)
print(type(arr))
print(id(arr))

1212746432848
[0 0 0 0 0 0 0 0 0 0]
[11 13 15 17 19 21 23 25 27 29]
<class 'numpy.ndarray'>
1212746432848


In [112]:
a2=np.arange(100,1,-10)
print(a2)

[100  90  80  70  60  50  40  30  20  10]


In [124]:
print(a2.sum())
print(np.sum(a2))
print(a2.min())
print(a2.max())
#print(a2.avg())--error
print(np.average(a2))
print(np.mean(a2))
#print(np.median(a2))

550
550
10
100
55.0
55.0


In [144]:
#create 3x3 array and find sum
array2d=np.array(([1,2,3],[5,6,7],[8,9,10]))
s=np.sum(array2d)
s1=np.sum(s)
print(s1)
print(array2d)
s=0
for i in array2d:
    for j in i:
        s+=j
print(s)
        

51
[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]
51


In [148]:
#add 2 single dimension array
a1=np.array(([1,2,3],[2,4,6]))
a2=np.array([4,5,6])
a3=a1+a2
print(a3)


[[ 5  7  9]
 [ 6  9 12]]


In [155]:
arr11=np.arange(5,10)
arr2=np.array([2])
a1=arr11*2
a2=arr11*arr2
print(a2)
print(a1)

[10 12 14 16 18]
[10 12 14 16 18]


In [171]:
#2d array using arange
a2d=np.arange(5,15).reshape(2,5)
print(a2d)
print("-------------")
a2d1=np.arange(1,11).reshape(2,5)
print(a2d1)
print("-------------")
print(a2d+a2d1)
a2d1=np.arange(1,6).reshape(1,5)

print("-------------")
print(a2d+a2d1)

[[ 5  6  7  8  9]
 [10 11 12 13 14]]
-------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
-------------
[[ 6  8 10 12 14]
 [16 18 20 22 24]]
-------------
[[ 6  8 10 12 14]
 [11 13 15 17 19]]


In [192]:
a2d=np.arange(5,15).reshape(2,5)
print(a2d)
print("sum is:",np.sum(a2d))
s=np.sum(a2d,axis=0,keepdims=True)
print("row sum:",s)
s1=np.sum(a2d,axis=1,keepdims=True)#sum col
print("col sum:",s1)


[[ 5  6  7  8  9]
 [10 11 12 13 14]]
sum is: 95
row sum: [[15 17 19 21 23]]
col sum: [[35]
 [60]]


In [203]:
#min from each row and avergae of each col
a2=np.arange(5,15).reshape(2,5)
print(a2)
print("minimun is",np.min(a2,axis=1,keepdims=2))
print("average is",np.average(a2,axis=0))

[[ 5  6  7  8  9]
 [10 11 12 13 14]]
minimun is [[ 5]
 [10]]
average is [ 7.5  8.5  9.5 10.5 11.5]


In [209]:
#random values
a1d=np.random.random()#range is from 0 to 1
print(a1d)
print(np.random.random(10))
print(np.random.randint(1,10))#random number from specified from 1 to 10
print(np.random.uniform(1,10,15))#generates random float number specified
print(np.random.randint(1,10,10))


0.18654629386867516
[0.919067   0.53112377 0.29244567 0.95789348 0.79154734 0.72272241
 0.58708059 0.07223084 0.61017626 0.59548413]
3
[8.77940685 5.33045364 5.7707834  3.75840319 7.23001256 5.335858
 2.25350655 2.42401441 7.30931728 5.93686379 3.95970659 3.3097396
 2.41602701 9.53654398 7.84281495]
[7 6 2 3 5 3 5 2 4 3]


In [217]:
#2d using random values
a=np.random.randint(5,15,(2,5))
print(a)
b=np.random.uniform(5,15,(2,5))
print(b)

[[10  5 14  7 14]
 [ 7  7  5 12  5]]
[[ 5.4609342  10.23914591  7.68902934  7.0199858   7.56203223]
 [12.37750953  7.00390746 10.58334908  8.37774819  7.54125206]]


In [264]:
a=np.random.randint(5,16,(4,4))
print(a)
print("-------------------------")
print(a[::])
print("-------------------------")
print(a[0::,0:2:])
print("-------------------------")
print(a[0::,2:4:])
print("-------------------------")
a3=(a[1:3:,1:3])
print(a3)
c=np.sum(a3)
print("sum",c)
print("-------------------------")

a3=(a[1::2,1::2])

print(a3)


[[ 5  9 12  5]
 [11 11 12  7]
 [12  5  6 15]
 [11  7  7 15]]
-------------------------
[[ 5  9 12  5]
 [11 11 12  7]
 [12  5  6 15]
 [11  7  7 15]]
-------------------------
[[ 5  9]
 [11 11]
 [12  5]
 [11  7]]
-------------------------
[[12  5]
 [12  7]
 [ 6 15]
 [ 7 15]]
-------------------------
[[11 12]
 [ 5  6]]
sum 34
-------------------------
[[11  7]
 [ 7 15]]


In [267]:
a1=np.random.randint(5,10,5)
a2=np.random.randint(200,215,8)
print(np.concatenate([a1,a2]))

[  7   8   8   6   7 200 212 203 212 205 210 214 211]


In [269]:
a1=np.random.randint(5,25,15).reshape(5,3)
a2=np.random.randint(200,215,15).reshape(5,3)
print(np.concatenate([a1,a2]))

[[ 21  17  14]
 [ 14  21  16]
 [ 14  20  24]
 [ 15  21  15]
 [ 16  14   6]
 [212 203 202]
 [207 200 201]
 [201 203 212]
 [210 212 208]
 [207 200 201]]


In [273]:
#hstack--col wise
print(np.hstack((a1,a2)))

[[ 21  17  14 212 203 202]
 [ 14  21  16 207 200 201]
 [ 14  20  24 201 203 212]
 [ 15  21  15 210 212 208]
 [ 16  14   6 207 200 201]]


In [274]:
#vstack-row wise
print(np.vstack((a1,a2)))

[[ 21  17  14]
 [ 14  21  16]
 [ 14  20  24]
 [ 15  21  15]
 [ 16  14   6]
 [212 203 202]
 [207 200 201]
 [201 203 212]
 [210 212 208]
 [207 200 201]]


In [275]:
#transpose
print(a1)
print("------------------------------------")
print(a2)
print("------------------------------------")
print(np.transpose(a1))

[[21 17 14]
 [14 21 16]
 [14 20 24]
 [15 21 15]
 [16 14  6]]
------------------------------------
[[212 203 202]
 [207 200 201]
 [201 203 212]
 [210 212 208]
 [207 200 201]]
------------------------------------
[[21 14 14 15 16]
 [17 21 20 21 14]
 [14 16 24 15  6]]


In [282]:
a1>15


array([[ True,  True, False],
       [False,  True,  True],
       [False,  True,  True],
       [False,  True, False],
       [ True, False, False]])

In [284]:
a1[a1>15]

array([21, 17, 21, 16, 20, 24, 21, 16])

In [286]:
#sum of even ele
np.sum(a1[a1%2==0])

138

In [288]:
#array ele >3
np.where(a1>15,a1,0)

array([[21, 17,  0],
       [ 0, 21, 16],
       [ 0, 20, 24],
       [ 0, 21,  0],
       [16,  0,  0]])

In [294]:
#1d array where odd number
arra=np.array([0,1,2,3,4,5])
print(np.where(arra%2==0,arra,arra*arra))

[ 0  1  2  9  4 25]


In [310]:
a10=np.array([45,7,np.nan,23,24,np.nan])
print(a10)
print(np.where(np.isnan(a10),a10,a10**2))
print(a10)

[45.  7. nan 23. 24. nan]
[2025.   49.   nan  529.  576.   nan]
[45.  7. nan 23. 24. nan]


In [315]:
#flatten #doesnt effect original array
a=np.random.randint(5,16,(4,4))
print(a)
s1=a.flatten()
print(s1)

[[14 12 14  7]
 [14  5  7  9]
 [14 14 14 11]
 [ 7 12  8  9]]
[14 12 14  7 14  5  7  9 14 14 14 11  7 12  8  9]


In [316]:
#ravel
a22=a.ravel()
print(a22)

[14 12 14  7 14  5  7  9 14 14 14 11  7 12  8  9]


In [317]:
a1=np.array([1,2,3])
a2=np.array([1,2,3])
a1.dot(a2)

14