# Assignment-2

In [3]:
import numpy as np

In [20]:
#1.Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).
a_1d=np.array([[1,2,3],[1,2,3]])
a1=np.array([6,3,4])
a_1d+a1

array([[7, 5, 7],
       [7, 5, 7]])

In [21]:
#2. How to replace all missing values with 0 in a numpy array?
a7=np.array([45,7,np.nan,23,24,np.nan])
print(a7)
a8=np.where(np.isnan(a7),0,a7)
print(a8)

[45.  7. nan 23. 24. nan]
[45.  7.  0. 23. 24.  0.]


In [22]:
#3.How to get the second largest value of an array when grouped by another array?
x = np.arange(1,10+1)
print("Original array:",x)
print (x[np.argsort(x)[:]])

Original array: [ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [23]:
#4.Write a NumPy program to create a 3x3x3 array with random values. 
a7=np.random.random((3,3,3))
print(a7)

[[[0.26161172 0.49700468 0.99198256]
  [0.55775651 0.10991398 0.97818433]
  [0.60187174 0.82771886 0.67321418]]

 [[0.37422071 0.62851907 0.45786791]
  [0.67487873 0.4662748  0.02683549]
  [0.0653194  0.02119666 0.27240349]]

 [[0.98705089 0.67616971 0.20176178]
  [0.15921599 0.52566067 0.33796135]
  [0.60323655 0.65566138 0.56435439]]]


In [24]:
#5. Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.
a=np.random.randint(1,10,15)
print(a)
print('**************')
a[a.argmax()] = -1
print(a)


[8 1 3 3 8 9 4 6 7 6 4 4 6 8 1]
**************
[ 8  1  3  3  8 -1  4  6  7  6  4  4  6  8  1]


In [25]:
#6.Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ",x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array:  [[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [26]:
#7.Write a NumPy program to get the unique elements of an array. 
a=np.array([1,1,2,3,4,8,8])
b=np.unique(a)
print(b)

[1 2 3 4 8]


In [27]:
#8.Write a NumPy program to get the powers of an array values element-wise.
a=np.arange(1,10)
print('a:',a)
print('powers of a:',a**2)

a: [1 2 3 4 5 6 7 8 9]
powers of a: [ 1  4  9 16 25 36 49 64 81]


In [28]:
#9.Write a NumPy program to remove the negative values in a NumPy array with 0.
c=np.array([1,2,-4,5,6,-9,-8,6,55])
print(np.where(c>0,c,0))

[ 1  2  0  5  6  0  0  6 55]


In [29]:
#10.Write a NumPy program to calculate the absolute value element-wise. 
b=np.array([1,1.2,2,2.2,3,1j])
print(np.abs(b))

[1.  1.2 2.  2.2 3.  1. ]


In [30]:
#11.Write a NumPy program to replace odd number in 2d array by its square . 
a1=np.random.randint(1,10,(3,3))
print(np.where(a1%2!=0,a1,a1**2))

[[64  7  5]
 [36  5  5]
 [ 5  5 36]]
